### ISSUE TITLE
[Bug] Dead loggers do not lead to program termination when exceptions occur in the python callback

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pyradiotracking#14]
There seems to be a rare case, in which a dead logger leads to a process failing instead of restarting / terminating the program.

```
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: INFO:radiotracking.analyze:SDR 0 recv 131072, clock drift: -0.021 s, filtered 0 / 0 signals, block len: 43.7 ms, compute: 20.8 ms
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: INFO:radiotracking.analyze:SDR 2 recv 131072, clock drift: -0.026 s, filtered 0 / 0 signals, block len: 43.7 ms, compute: 18.0 ms
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: INFO:radiotracking.analyze:SDR 1 recv 131072, clock drift: -0.024 s, filtered 0 / 0 signals, block len: 43.7 ms, compute: 21.5 ms
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: INFO:radiotracking.analyze:SDR 3 recv 131072, clock drift: -0.052 s, filtered 0 / 0 signals, block len: 43.7 ms, compute: 18.9 ms
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: /usr/lib/python3/dist-packages/numpy/ctypeslib.py:527: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   return array(obj, copy=False)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: WARNING:radiotracking.analyze:SDR 3 total clock drift (0.14707 s) is larger than two blocks, signal detection is degraded. Resyncing...
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: /usr/lib/python3/dist-packages/scipy/signal/spectral.py:1773: UserWarning: nperseg = 256 is greater than input length  = 0, using nperseg = 0
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   .format(nperseg, input_length))
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: Traceback (most recent call last):
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "_ctypes/callbacks.c", line 232, in 'calling callback function'
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 612, in _bytes_converter_callback
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     self._callback_bytes(values, context)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 659, in _samples_converter_callback
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     self._callback_samples(iq, context)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 154, in process_samples
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     signals = self.extract_signals(freqs, times, spectrogram, ts_start)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 227, in extract_signals
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     signal_min_duration_num = self.signal_min_duration / (times[1] - times[0])
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: IndexError: index 1 is out of bounds for axis 0 with size 0
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: WARNING:radiotracking.analyze:SDR 3 total clock drift (0.020442 s) is larger than two blocks, signal detection is degraded. Resyncing...
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: Traceback (most recent call last):
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "_ctypes/callbacks.c", line 232, in 'calling callback function'
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 612, in _bytes_converter_callback
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     self._callback_bytes(values, context)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 659, in _samples_converter_callback
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     self._callback_samples(iq, context)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 154, in process_samples
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     signals = self.extract_signals(freqs, times, spectrogram, ts_start)
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 227, in extract_signals
Mar 19 11:13:40 jonas-rpi-00001 python3[970]:     signal_min_duration_num = self.signal_min_duration / (times[1] - times[0])
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: IndexError: index 1 is out of bounds for axis 0 with size 0
Mar 19 11:13:40 jonas-rpi-00001 python3[970]: WARNING:radiotracking.analyze:SDR 3 total clock drift (0.008299 s) is larger than two blocks, signal detection is degraded. Resyncing...
```

**Comment by jonashoechst** [comment]
A redundant watchdog system was introduced in fb44944 which should fix this error and other potential errors related to incorrect analyzer process termination.
