### ISSUE TITLE
Found new error message on mof-rts-00007 before receiver silently does not receive any signals. 

### ISSUE THREAD

**Issue by lampep** [Nature40/pyradiotracking#23]
the following message seems new to me and maybe it isn't handelt at the moment and can be a point to throw an eye on.
```
/usr/lib/python3/dist-packages/numpy/ctypeslib.py:527: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
```

```
Apr 05 12:16:17 mof-rts-00007 bash[13730]: Process SignalAnalyzer-1:
Apr 05 12:16:17 mof-rts-00007 bash[13730]: Traceback (most recent call last):
Apr 05 12:16:17 mof-rts-00007 bash[13730]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
Apr 05 12:16:17 mof-rts-00007 bash[13730]:     self.run()
Apr 05 12:16:17 mof-rts-00007 bash[13730]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 103, in run
Apr 05 12:16:17 mof-rts-00007 bash[13730]:     self.sdr.read_samples_async(self.process_samples, self.sdr_callback_length)
Apr 05 12:16:17 mof-rts-00007 bash[13730]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 632, in read_samples_async
Apr 05 12:16:17 mof-rts-00007 bash[13730]:     self.read_bytes_async(self._samples_converter_callback, num_bytes, context)
Apr 05 12:16:17 mof-rts-00007 bash[13730]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 577, in read_bytes_async
Apr 05 12:16:17 mof-rts-00007 bash[13730]:     raise LibUSBError(result, 'Could not read %d bytes' % (num_bytes))
Apr 05 12:16:17 mof-rts-00007 bash[13730]: rtlsdr.rtlsdr.LibUSBError: <LIBUSB_ERROR_NOT_FOUND (-5): Entity not found> "Could not read 600000 bytes"
Apr 05 12:16:17 mof-rts-00007 bash[13730]: Found Rafael Micro R820T tuner
Apr 05 12:16:18 mof-rts-00007 bash[13730]: [R82XX] PLL not locked!
Apr 05 12:16:18 mof-rts-00007 bash[13730]: Process SignalAnalyzer-2:
Apr 05 12:16:18 mof-rts-00007 bash[13730]: Traceback (most recent call last):
Apr 05 12:16:18 mof-rts-00007 bash[13730]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
Apr 05 12:16:18 mof-rts-00007 bash[13730]:     self.run()
Apr 05 12:16:18 mof-rts-00007 bash[13730]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 103, in run
Apr 05 12:16:18 mof-rts-00007 bash[13730]:     self.sdr.read_samples_async(self.process_samples, self.sdr_callback_length)
Apr 05 12:16:18 mof-rts-00007 bash[13730]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 632, in read_samples_async
Apr 05 12:16:18 mof-rts-00007 bash[13730]:     self.read_bytes_async(self._samples_converter_callback, num_bytes, context)
Apr 05 12:16:18 mof-rts-00007 bash[13730]:   File "/usr/local/lib/python3.7/dist-packages/rtlsdr/rtlsdr.py", line 577, in read_bytes_async
Apr 05 12:16:18 mof-rts-00007 bash[13730]:     raise LibUSBError(result, 'Could not read %d bytes' % (num_bytes))
Apr 05 12:16:18 mof-rts-00007 bash[13730]: rtlsdr.rtlsdr.LibUSBError: <LIBUSB_ERROR_NOT_FOUND (-5): Entity not found> "Could not read 600000 bytes"
Apr 05 12:16:18 mof-rts-00007 bash[13730]: Allocating 15 zero-copy buffers
Apr 05 12:16:18 mof-rts-00007 bash[13730]: Found Rafael Micro R820T tuner
Apr 05 12:16:19 mof-rts-00007 bash[13730]: [R82XX] PLL not locked!
Apr 05 12:16:19 mof-rts-00007 bash[13730]: Allocating 15 zero-copy buffers
Apr 05 12:16:34 mof-rts-00007 bash[13730]: /usr/lib/python3/dist-packages/numpy/ctypeslib.py:527: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
Apr 05 12:16:34 mof-rts-00007 bash[13730]:   return array(obj, copy=False)
Apr 05 12:16:34 mof-rts-00007 bash[13730]: WARNING:radiotracking.analyze:SDR 0 total clock drift (0.97416 s) is larger than two blocks, signal detection is degraded. Terminating...
Apr 05 12:16:35 mof-rts-00007 bash[13730]: Found Rafael Micro R820T tuner
Apr 05 12:16:36 mof-rts-00007 bash[13730]: [R82XX] PLL not locked!
Apr 05 12:16:36 mof-rts-00007 bash[13730]: Allocating 15 zero-copy buffers
Apr 05 16:18:27 mof-rts-00007 systemd[1]: Stopping RadioTracking...
```

**Comment by jonashoechst** [comment]
As discussed in #14 an new redundant observation function was implemented, which should fix non-termination of failed analyzers. (see fb44944)
