### ISSUE TITLE
Bug: Signal creation crashes in c81e16c7d87ff38f498dc64f9cc43547b4329755

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pyradiotracking#25]
```
Feb 14 13:23:32 umr-test-00001 bash[2371]: INFO:radiotracking.analyze:SDR 0 received data at 1644841412.248328
Feb 14 13:23:32 umr-test-00001 bash[2371]: Exception ignored on calling ctypes callback function: <bound method RtlSdr._bytes_converter_callback of <rtlsdr.rtlsdraio.RtlSdrAio object at 0x7f8ada9610>>
Feb 14 13:23:32 umr-test-00001 bash[2371]: Traceback (most recent call last):
Feb 14 13:23:32 umr-test-00001 bash[2371]:   File "/usr/local/lib/python3.9/dist-packages/rtlsdr/rtlsdr.py", line 612, in _bytes_converter_callback
Feb 14 13:23:32 umr-test-00001 bash[2371]:     self._callback_bytes(values, context)
Feb 14 13:23:32 umr-test-00001 bash[2371]:   File "/usr/local/lib/python3.9/dist-packages/rtlsdr/rtlsdr.py", line 659, in _samples_converter_callback
Feb 14 13:23:32 umr-test-00001 bash[2371]:     self._callback_samples(iq, context)
Feb 14 13:23:32 umr-test-00001 bash[2371]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 221, in process_samples
Feb 14 13:23:32 umr-test-00001 bash[2371]:     signals = self.extract_signals(freqs, times, spectrogram, ts_start)
Feb 14 13:23:32 umr-test-00001 bash[2371]:   File "/home/pi/pyradiotracking/radiotracking/analyze.py", line 425, in extract_signals
Feb 14 13:23:32 umr-test-00001 bash[2371]:     signal = Signal(self.device, ts.astimezone(pytz.utc), freq, duration, max_dBW, avg_dBW, std_dB, noise_dBW, snr_dB)
Feb 14 13:23:32 umr-test-00001 bash[2371]: TypeError: Can't instantiate abstract class Signal with abstract methods duration, frequency, ts
```

**Comment by jonashoechst** [comment]
The issue did only occur on a local development version and was at no point in time committed.
